name: build-and-test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    name: 'unit-tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: 'Install packages'
        run: npm install --frozen-lockfile
      - name: 'check tests'
        run: npm run test
      - name: 'check tests coverage'
        run: npm run coverage
  